### PR TITLE
Publish to NPM

### PR DESCRIPTION
**Pull request by Craga89**
Added package.json for NPM publishing. Can you merge this and do an `npm publish`? It would be great for those of us using a Webpack or Browserify workflow!

### CODE REVIEW

**Comment by davismj** [comment]
@EisenbergEffect I'm not really familiar with the cited workflow, but I can't see a reason not to publish to npm. Especially if @Craga89 can send me a link to a demo repo that uses the said workflow so that I can verify it works as desired.

**Comment by EisenbergEffect** [comment]
@Craga89 Can you send something to @davismj so he can explore.

**Comment by davismj** [comment]
Except that he couldn't really show me what the workflow looks like using npm until its on npm. It seems reasonable to merge and publish since we can always unpublish and delete the package.json if it doesn't work correctly.

**Comment by EisenbergEffect** [comment]
Published.

**Comment by davismj** [comment]
@Craga89 please try to create an example of your workflow so i can verify that the issue is resolved

**Comment by Craga89** [comment]
Here's an example repo I'll be updating soon to use the Durandal NPM package: https://github.com/craga89/durandal-webpack

**Comment by davismj** [comment]
Great. Please be sure to update the readme on how to use the npm package. Also, when do you expect that it will be udpated? Though it is not a huge risk to be on npm, I don't want anyone to become confused, especially if it doesn't work, so I'd like to get it tested and accepted as soon as possible.

**Comment by Craga89** [comment]
It works great FYI, since NPM just provides the files in this repo when installing, much like Bower. I've added some thin documentation to the Durandal repo built around the same syntax as the Bower page.

**Pull request merged**
